# Generated by Django 5.2.6 on 2025-12-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_safetyincident_location_safetyincident_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyincident',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='incident_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolving', 'Resolving'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20),
        ),
    ]
