# Generated by Django 5.2.5 on 2025-09-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('project_manager', 'Project Manager'), ('safety_officer', 'Safety Officer'), ('inventory_manager', 'Inventory Manager'), ('accounts_manager', 'Accounts Manager'), ('equipment_manager', 'Equipment Manager')], max_length=50, null=True),
        ),
    ]
