# Generated by Django 5.2.6 on 2025-11-02 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('project_manager', 'Project Manager'), ('safety_officer', 'Safety Officer'), ('inventory_manager', 'Inventory Manager'), ('production_manager', 'Production Manager'), ('equipment_manager', 'Equipment Manager')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('access_level', models.CharField(choices=[('None', 'None'), ('View', 'View'), ('Edit', 'Edit'), ('Full', 'Full')], max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('group', 'module')},
            },
        ),
    ]
