# Generated by Django 5.2.6 on 2025-12-26 23:15

from django.db import migrations, models

# 🔧 Step 1: Define the mapping function
def map_roles_to_integers(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    mapping = {
        "project_manager": 0,
        "safety_officer": 1,
        "inventory_manager": 2,
        "production_manager": 3,
        "equipment_manager": 4,
    }
    for user in CustomUser.objects.all():
        if isinstance(user.role, str) and user.role in mapping:
            user.role = mapping[user.role]
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_role_rolemodulepermission'),
    ]

    operations = [
        # 🔧 Step 2: Run the mapping before altering the field
        migrations.RunPython(map_roles_to_integers),

        # 🔧 Step 3: Alter the field to IntegerField
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[
                    (0, 'Project Manager'),
                    (1, 'Safety Officer'),
                    (2, 'Inventory Manager'),
                    (3, 'Production Manager'),
                    (4, 'Equipment Manager'),
                ],
            ),
        ),
    ]
