# Generated by Django 5.2.6 on 2026-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='role_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='access_level',
            field=models.CharField(choices=[('none', 'None'), ('view', 'View'), ('edit', 'Edit'), ('full', 'Full')], default='none', max_length=10),
        ),
        migrations.RemoveField(
            model_name='rolemodulepermission',
            name='group',
        ),
    ]
