# Generated by Django 5.2.6 on 2026-04-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_rolemodulepermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together={('role_id', 'module')},
        ),
    ]
