# Generated by Django 5.2.5 on 2026-04-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_rolemodulepermission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rolemodulepermission',
            name='permission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rolemodulepermission',
            name='access_level',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='rolemodulepermission',
            unique_together={('role_id', 'module', 'permission_id')},
        ),
    ]
