# Generated by Django 5.2.5 on 2025-08-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('assigned_team', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_projects', models.ManyToManyField(to='projects.project')),
                ('equipment', models.ManyToManyField(blank=True, related_name='projects', to='equipment.equipment')),
                ('inventory', models.ManyToManyField(blank=True, related_name='projects', to='inventory.inventory')),
            ],
        ),
    ]
