# Generated by Django 5.2.6 on 2026-01-03 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financerecord',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='financerecord',
            name='type',
        ),
        migrations.AddField(
            model_name='financerecord',
            name='category',
            field=models.CharField(choices=[('operations', 'Operations'), ('maintenance', 'Maintenance')], default='operations', max_length=20),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='financerecord',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financerecord',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
