# Generated by Django 5.2.6 on 2026-01-08 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=50)),
                ('income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('expenditure', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trucks', models.IntegerField()),
                ('federal_royalty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('state_haulage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('mou_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
