# Generated by Django 5.2.6 on 2026-04-28 21:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('item_name', models.CharField(max_length=200)),
                ('shift', models.CharField(blank=True, max_length=50, null=True)),
                ('target_quantity', models.IntegerField(default=0)),
                ('actual_quantity', models.IntegerField(default=0)),
                ('defective_quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_production_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
