# Generated by Django 5.2.6 on 2025-09-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('critical', 'Critical')], default='good', max_length=10),
        ),
    ]
