# Generated by Django 5.2.6 on 2026-02-21 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recent Activity', 'verbose_name_plural': 'Recent Activities'},
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('view', 'Viewed'), ('login', 'Logged In')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
