# Generated by Django 5.2.6 on 2025-09-27 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrecord',
            name='activity',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operationrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
